### ISSUE TITLE
Troubles with Atom on windows

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/120_CreativeCoding_Fall2017#14]
Is anyone else having trouble with Atom? I have had to download it twice it works but then today when I went to open it I can't get it to open. I just deleted it and re-downloaded it but wondering if it's just my computer? Thank you!

**Comment by michaelmusick** [comment]
Thank you for checking about this. I am currently unaware of any issues with atom on Windows. So please, if you are having similar issues, let us know. 

Rachel, what version of Windows are you running?

**Comment by rachel-holton-burnett** [comment]
No problem, thanks for replying so quickly! It's working fine now so we'll see what happens when I close it and try it again.

I'm running Windows 10.

**Comment by JonSwallow** [comment]
@rachel-holton-burnett You can check permissions on it by left clicking in your menu and selecting "open file location" left click on it there and select properties. Under the security tab you can change permissions if needed. Windows 10 is wonky on permissions but the basic ones from 7 are still there sometimes you have to go manually assign permissions.

**Comment by ewilsey** [comment]
@rachel-holton-burnett The only problem I had when downloading Atom was getting it to go into my WindowsApps folder because the folder itself was hidden and I did not have permission to view or alter it. I fixed this on my own by taking a similar path as @JonSwallow. After discovering the hidden file in my program file, I then went into properties and securities and changed permissions for that file to allow my Users profile to access it. But this is also where I had the most trouble because my Users profile was flagged as being corrupted and I ran a sfc in PowerShell only to have no problems detected. That helped me figure out that I needed to give permission to Users, not User (singular) and not Administrator. After I did that, Atom worked, the corrupted flag went away, and I felt much better.

**Comment by JonSwallow** [comment]
@rachel-holton-burnett  I found an article that probably will help much more definitively than my meager attempt.
[Changing Permissions in Windows10](http://winaero.com/blog/how-to-take-ownership-and-get-full-access-to-files-and-folders-in-windows-10/)

**Comment by rachel-holton-burnett** [comment]
Thanks everyone! It's continuing to work normally for now but I appreciate the insight! :)
