### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Glossyy** [Montana-Media-Arts/120_CreativeCoding_Fall2017#21]
I went to double check my submission for this week's homework and I get a 404 error when I click on my screenshot link. When I'm in atom my screenshot shows up with no problem in the preview. Am I missing something in my link that I'm not seeing? I commited it to github, pushed it, waited an hour or so and then tried again. Still no luck. 

![image](https://user-images.githubusercontent.com/23406493/30408949-a32e7f1a-98c7-11e7-862b-f3eaaf158e7b.png)

**Comment by michaelmusick** [comment]
Hey @Glossyy, this may seem crazy minor, but your readme.md file links to `Screenshot-markdown-in-atom.png`. Where as your image filename is `Screenshot-markdown-in-atom.PNG`.

I believe it is because your file extension is capitalized in the repo (`.PNG`) and not in the readme document. Would you please change this and let us know if it fixes the problem?

**Comment by mjohnson92** [comment]
Watch out for capitals! I've already messed myself a few times with them.

**Comment by MikeStevens1161** [comment]
Spacing is what keeps getting me. That has messed me up quite a bit.

**Comment by rachel-holton-burnett** [comment]
Thank you so much for this thread! I had the same problem. The file name has to match perfectly (it is case sensitive).

**Comment by Glossyy** [comment]
Well.... the capitalization fixed it. Thanks all! @rachel-holton-burnett glad it helped you too!

**Comment by madisonflaget** [comment]
I had the exact same problem with capitalization. Its good to know that I wasn't the only one lol

**Comment by lbecker137** [comment]
I definitely keep having issues with spacing. Syntax will really get ya.
