### ISSUE TITLE
Homework Files

### ISSUE THREAD

**Issue by kaitlinclifford** [Montana-Media-Arts/120_CreativeCoding_Fall2017#33]
Is there a way to delete a bunch of files at once instead of going into each individual file and deleting it? I couldn't find a delete button other than on each individual item. I messed up when uploading the stuff to github and it took a while to go in and delete every single thing i had just committed.

**Comment by JonSwallow** [comment]
@kaitlinclifford I had to go try this before I suggested it. Any file or group of files or folders within your repository on your computer that you delete or create or change, the same change is reflected on GitHub whenever you push it from Github Desktop. To be sure I created a testdelete folder in my 120-work folder with a file in it. I pushed it then checked to make sure it was present on Github. I then deleted it on my computer re-pushed it and presto chango it was gone from Github. Hope that helps.

**Comment by kaitlinclifford** [comment]
I don't know how, but somehow from deleting the files here on github, then going back to the github on my desktop and then to atom, my files got deleted in atom. So if I delete things here on github, will it delete them in atom? I'm having troubles

**Comment by michaelmusick** [comment]
@kaitlinclifford 

So, I think I know what is happening. You created the repo, then made a buncgh of changes (added a bunch of files, from the _MACOSX folder or whatever, instead of ‘empty-example’. Then synced, all of these changes to GitHub, only to realize you didnt want them there? 

So, you delete everything on GitHub.com <http://github.com/>, re-sync your repo with your local copy, and find everything gone?

(That is at least what it looks like on your repo.) 

The answer to your question is yes. If you delete a file on GitHub, then sync that change with your computer, you have thereby also deleted the file on your computer. Luckily nothing is ever truly deleted when using Git though, so if you deleted things you did not mean to, this can be fixed. It is just hard to explain over text-based messages.

Is this what is going on?

**Comment by JonSwallow** [comment]
@kaitlinclifford  I would only delete from my repository on my machine. It is the file directory that is the repository this is what we designated as our repository. The main interaction you need to worry about is between that file repository and Github desktop. There is a way you can view your changes if you lost any work. At the toolbar on top of Github desktop app click view then history. You should see a history of your changes. Click on the change you want to recover and it will come up I would then copy and paste this back into the appropriate file.

**Comment by michaelmusick** [comment]
This is a pretty good explanation!

**Comment by kaitlinclifford** [comment]
@michaelmusick your explanation is what happened. If I upload stuff to github and it's not what I want, but don't want to delete my work in atom what should I do? I think I'm just going to start over and then when I upload it, be careful about which stuff I upload. And @JonSwallow I totally get what you're saying, and I will probably try that when I have spare time to look things over

**Comment by mmusick** [comment]
First, I am glad we at least understood what happened. Second, the beauty of Git and GitHub, is that we can change things, even after uploading them. Nothing is set in stone, because it is all stored in Git’s version control system. So, it is all based on commits anyways. 

If you upload a file, that you later realize you don’t want to be part of your Git repo, you should delete it. 

If you upload a file, that you later realize needs changes, you should not delete it, but instead, change it on your local machine. Commit those changes, and then re-sync to the remote (GitHub.com <http://github.com/>).

Does that make sense the way I described it, or does it sound like jibberish?

**Comment by kaitlinclifford** [comment]
Ok. That all does make sense. I think that next week if I have problems like this again I will follow that. But right now I feel like it's easier to redo everything and upload it again. Maybe I can come to your office hours sometime so that you can help me understand it better

**Comment by michaelmusick** [comment]
Yes, do what you must to get the assignment done. And absolutely, if you had some time, it would be wonderful for you to come by, as I would be more than happy to try and help make more clear what is occurring with Git.

**Comment by kaitlinclifford** [comment]
Do you have set office hours, or kind of just whenever?

**Comment by michaelmusick** [comment]
I do have set office hours, they are listed under the [“Instructor”](https://montana-media-arts.github.io/creative-coding-1/instructor/ <https://montana-media-arts.github.io/creative-coding-1/instructor/>)

Also, they are;

- Tuesday: 11:30am - 1:30pm
- Wednesday: 2:30pm - 4:00pm

If you cannot make those, I can try to work with you to find another time. But as I am incredibly busy, I would appreciate it if you try to make the posted hours. 

Looking forward to meeting you and working with you in person sometime. (This is true for all of you in the class. Please feel free to come by my office hours!)

**Comment by kaitlinclifford** [comment]
Alright. Thank you for all the help with this issue I'm having. And thanks for the office hours, I'll probably stop by at one of those.

**Comment by kaitlinclifford** [comment]
I know I keep asking a lot of questions, but I'm confused again. I'm putting a picture of my github desktop to know if this is what I'm supposed to do. It says 141 changed files. Do I need to go through all of them and check/ uncheck each one if I need or don't need it? I should I just commit to master and then push all of them?
![github example](https://user-images.githubusercontent.com/31676610/30947211-a349472e-a3c5-11e7-9aae-0ce178c84a6a.png)

**Comment by JonSwallow** [comment]
@kaitlinclifford  the green plus opens up the folder. Personally I would just go find my code for the hw assignments and the readme.md files.  You can always redownload that empty example again and work off of it for structure. You can also click on any persons name and go look at their repository for structure reference. Here is a screenshot where I got to the source of what I wanted and highlighted the code I would then copy and paste into a new readme.md. You might want to just get your code files and store them say on your desktop until you get your folders structured the way you want then commit and push after you have it set up the way you want it. 
![clipboard02](https://user-images.githubusercontent.com/31550331/30947571-b927ed82-a3c7-11e7-8031-7096ce914ef4.jpg)

**Comment by JonSwallow** [comment]
@kaitlinclifford  Here is what the structure should look like. Sorry for my terrible handwriting but I think you can get it from this. The crossed out files are not needed. 
![sketch](https://user-images.githubusercontent.com/31550331/30948251-d43aca32-a3cb-11e7-9bed-493c72bf7c6b.png)

**Comment by kaitlinclifford** [comment]
oh awesome... Thank you. that really helps me. I'll be sure to have mine look like that!!
