### ISSUE TITLE
Uploading

### ISSUE THREAD

**Issue by Benji0130** [Montana-Media-Arts/120_CreativeCoding_Fall2017#35]
When I saved my homework, I don't see it popping up as it should have.

**Comment by madisonflaget** [comment]
Can you specify what you mean by "popping up"? 

Are you referring to when you are writing the sketch.js file and need to test it? If so, after you save it you need to open the index.html file in the browser (see the class website week 3).

If you are referring to the part where you submit the homework. It is likely because you haven't "pushed" the info to GitHub yet. Saving your code on you laptop it like saving a draft email. Yes, it is saved, but no one can see it until you hit send. Pushing is how you  send that "email" to Github. See week two lesson for how to push.

**Comment by JakeTheFlare** [comment]
Like @madisonflaget said,...

You need to open the index.html file in your web browser to view your sketch, not the sketch.js file.

As for the submitting your homework part.  I usually log on to my GitHub Desktop, and then commit the changes I make to the master server.  (See this [link](https://montana-media-arts.github.io/creative-coding-1/modules/week-2/git-gui-github/) for a refresh on the GitHub Desktop.)
