### ISSUE TITLE
having trouble with live-preview in Atom and Brackets. 

### ISSUE THREAD

**Issue by Cassidy7396** [Montana-Media-Arts/120_CreativeCoding_Fall2017#48]
I cant get the live preview to work in brackets or atom.
they both display an error message whenever I try and I've already tried to delete and re-download both programs and it still doesn't work. Pleas help.

**Comment by JonSwallow** [comment]
@Cassidy7396  If you cannot get the preview to work, you can always go to your html file directly in your directory and click it that will open it in your browser and you can preview from there. Not much of a work around but it should do the trick.

**Comment by madisonflaget** [comment]
![inkedscreenshot 2017-10-13 12 35 44_li](https://user-images.githubusercontent.com/21345991/31560969-a11be8da-b013-11e7-9c64-2fe5e8db7e7a.jpg)
You can open this easily via the package "open-in-browsers" in that Michael had us add to Atom at the beginning of the semester. Right click the index.html file, hover over "Open in browsers", then select the browser you want. As I mentioned before, Internet Explorer and Edge will often have issues displaying. I recommend , Chrome, Firefox, or Safari.
![inkedscreenshot 2017-10-13 12 36 59_li](https://user-images.githubusercontent.com/21345991/31560965-9db20a62-b013-11e7-8bb2-0b8dce636cd7.jpg)

**Comment by quintinbruderer** [comment]
I just now realized that ya'll have open in browserS. (Although I believe that is the better of the two...) I have open in browser (no s). Opens in your default browser. 
Try [this](https://atom.io/packages/open-in-browser) package instead.

You will still need to use it on your HTML, not your js file. Shift Command Q on a mac, but seeing you're on PC I don't know of the top of my head.

**Comment by madisonflaget** [comment]
I'm sure that there's nothing wrong with using "open-in-browser" but "open-in-browsers" is the package that Michael recommended downloading. It may be less convenient than yours, but I like that it give you the option to choose a different browser. With any digital design, it's important to test in MULTIPLE browsers because sometimes things will display differently in different browsers. It's a good habit to get into.

<img width="960" alt="screenshot 2017-10-18 08 59 59" src="https://user-images.githubusercontent.com/21345991/31725927-ca74a29e-b3e2-11e7-91cc-661545b97b81.png">
