### ISSUE TITLE
Reset Growing Circle

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#53]
I was just messing around with how to get a circle to grow. I'd like it to reset once it hits the edges, but can't figure it out. Also going to try to work this into a for loop if I can, but not sure where to start. Any suggestions would be great. Thanks!

[see code](https://github.com/StuffnThingz/120-work/blob/master/hw-8/sketch.js)

**Comment by JonSwallow** [comment]
@StuffnThingz  I messed about with it for a minute Toby. I believe you are going to have to make the condition change to make it reverse. You have set a condition x >= width, then you have, at the bottom incremented x. So you will have to probably use a nested statement somehow, and also change the condition of x.  Perhaps  using mouse X instead of  x= 25. I am flooded with other stuff but I think if you look in that direction it should help. I hope that helps a little.
