### ISSUE TITLE
mousePressed question

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#60]
Trying to get these arrows to fire more than one at a time with mousePressed. Want them to come from the left of the screen in random order every time you click the mouse. Figured it out with just refreshing the page, but what it to happen with mousePressed. 

[example of arrows coming from left of screen] - (https://github.com/StuffnThingz/120-work/blob/master/practice%20folder/sketch.js)
[what i have so far with mousePressed] - (https://github.com/StuffnThingz/120-work/blob/master/hw-11/sketch.js)

**Comment by JonSwallow** [comment]
@StuffnThingz, Hey Tobin I saw this earlier was hoping someone would answer by now. I ran the second one and I think it is a great idea and it works well. I am not sure of a solution because when mouse pressed you are creating a new arrow every time as opposed to creating like 20 of whatever object. To get it to fire continuously use the mouseReleased function. I don't have a solution I just wanted to tell you that to take that code and create that firing function was really creative. That and I did not want you to feel like no one was paying attention. I hope you had a good holiday. Cheers!!!!
